### ISSUE TITLE
Mention separate dev branch in README

### ISSUE THREAD

**Issue by garrison** [JuliaArrays/ElasticArrays.jl#10]
It would be nice if the README mentioned there is a separate dev branch.  I realize gitflow is a common pattern, but most julia projects I know of tend to merge things directly to master if they pass tests.  As of last night, master had not been updated since April, and knowing that there was development elsewhere would have saved me the time I spent fixing deprecations on the master branch in #9.

Anyway, thanks again :100: for the package and fixing it to work on julia 1.0.

**Comment by oschulz** [comment]
The dev branch isn't really meant to be long-lived, I mainly use it when I don't have a fancy name for a short-lived feature branch. I just kinda forgot to update master, sorry.

As for #9, it was actually quite helpful to me (e.g. the Travis fix, forgot part of it, putting it in right now) - thanks for helping out! Any sorry about that duplicate `test_A` function, that shouldn't have been in there ... ...

**Comment by garrison** [comment]
Ok great!  Glad to hear it was helpful.  I'm going to close this issue then, doesn't sound like it makes sense to update the README after all.

**Comment by oschulz** [comment]
Still, you're right, that branch should have been named 1.0-compat - I got rid of the dev branch for now. It can be a place for long-lived experimental features in the future, but PR's against master will have priority over them.

**Comment by garrison** [comment]
> that branch should have been named 1.0-compat

If you are looking in the future to draw attention to such a branch, I'd recommend opening a WIP (work-in-progress) pull request for it as well.  Speaking personally, I'll admit I would have been far more likely to notice it this way than if a branch had existed without an associated pull request.

**Comment by oschulz** [comment]
Good point about doing a PR for such things, I'll keep it in mind, thanks!
