### ISSUE TITLE
Remove from Appveyor

### ISSUE THREAD

**Issue by oschulz** [JuliaArrays/ElasticArrays.jl#18]
I switched CI testing to Travis-only (also for Windows), works fine, but Appveyor now generates errors on each build (no Appveyor config file anymore, obviously).

I don't have permissions to remove ElasticArrays.jl from JuliaArrays on Appveyor - @timholy, @ChrisRackauckas do you know who does?

**Comment by oschulz** [comment]
Gentle bump @timholy, @ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
AppVeyor doesn't run on org accounts, it runs on personal accounts. And I don't have admin here.

**Comment by oschulz** [comment]
Normally, yes, but Appveyor does support account for GitHub orgs:

    https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

The AppVeyor address for ElasticArrays is

    https://ci.appveyor.com/project/JuliaArrays/elasticarrays-jl

so it looks like an AppVeyor org account, but I don't know who owns it. ElasticArrays used to be on my personal GitHub, but was moved (by @timholy ? I don't remember anymore) to "project/JuliaArrays" on AppVeyor when we moved ElasticArrays to JuliaArrays.

**Comment by oschulz** [comment]
I contacted the AppVeyor support - @c42f, looks like you're the owner of JuliaArrays/ElasticArrays.jl on AppVeyor, could you delete it (only on AppVeyor, not on GitHub, of course)?

**Comment by c42f** [comment]
Done!

**Comment by oschulz** [comment]
Thanks!
