### ISSUE TITLE
Add type aliases for Vector and Matrix?

### ISSUE THREAD

**Issue by ShuhuaGao** [JuliaArrays/ElasticArrays.jl#27]
Julia has aliases for 1D and 2D arrays named `Vector` and `Matrix` respectively.  I feel it is convenient to use them to indicate explicitly that we are dealing with a 1D or 2D arrays, e.g., in a function interface.  Is it a good idea to supply such aliases in `ElasticArrays` for consistency? 
E.g., 
```julia
const ElasticVector{T} = ElasticArray{T, 1}
const ElasticMatrix{T} = ElasticArray{T, 2}
```

**Comment by oschulz** [comment]
Hm, I'm not sure - in the case of a vector, one would probaby use a a standard `Vector` instead of an `ElasticArray`, I assume.

**Comment by ShuhuaGao** [comment]
> one would probably use a standard `Vector` instead of an `ElasticArray`

Yes, I agree. That said, it is not bad to include such aliases in my option, since the prefix `Elastic` helps to avoid polluting global namespace.  Give users a choice, and they can decide whether to use it 😀.

**Comment by oschulz** [comment]
Sure, I'm not against it - would you like to do a PR?

**Comment by ShuhuaGao** [comment]
Yes. I will do it later when I am with my PC.
