### ISSUE TITLE
Missing a bunch of array interface overloads?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/ElasticArrays.jl#32]
Things used to work, but now it seems like ElasticArrays are missing a bunch of array interface overloads.

https://github.com/SciML/OrdinaryDiffEq.jl/pull/1337

```julia
Base.similar(x::ElasticArrays.ElasticArray, ::Type{T}) where T = deepcopy(x)
Base.copy(x::ElasticArrays.ElasticArray) = deepcopy(x)
Base.zero(x::ElasticArrays.ElasticArray) = ElasticArray(zero(Array(x)))
Base.resize!(x::ElasticArrays.ElasticArray,i::Tuple) = resize!(x,i...)
```

is what I had to do to my test to make it work (those are all fairly hacky versions), so I'm confused why those are no longer defined. They return `Array`.

**Comment by oschulz** [comment]
Oops, Ok, I'll get right on it.

**Comment by oschulz** [comment]
This is strange, with ElasticArrays v1.2.4 (and without the overloads above) I get

```
Base.similar(ElasticArray{Float32}(undef, 2, 5), Float64) isa ElasticArray{Float64}
Base.copy(ElasticArray{Float32}(undef, 2, 5)) isa ElasticArray{Float32}
Base.zero(ElasticArray{Float32}(undef, 2, 5)) isa ElasticArray{Float32}
Base.resize!(ElasticArray{Float32}(undef, 2, 5), 2, 10) isa ElasticArray{Float32}
```
as expected (also on Julia v1.6.0-beta1).

On the other hand, `resize!(x::ElasticArrays.ElasticArray,i::Tuple)` was never defined for `ElasticArray`, so that should never have worked in the past as well.

**Comment by ChrisRackauckas** [comment]
It could be the Adapt.jl upper bound causing issues?

**Comment by oschulz** [comment]
Fixing that bound right now ...

**Comment by oschulz** [comment]
Here we go: https://github.com/JuliaRegistries/General/pull/28769 :-)

**Comment by oschulz** [comment]
I think we fixed this one, right?
