### ISSUE TITLE
Should Base.similar be overridden?

### ISSUE THREAD

**Issue by garrison** [JuliaArrays/ElasticArrays.jl#4]
I'm not a fan of 6fcfa52e54.  With this change, multiplying an `ElasticArray` matrix by a regular matrix results in an `ElasticArray`, not a `Matrix`.  Chances are, if I am performing an operation on an `ElasticArray`, I am looking for it to return a non-elastic array.  I think it is non-standard to override `Base.similar` in this way.

**Comment by oschulz** [comment]
Good point. Check out #5, would that work for you?
