### ISSUE TITLE
Feature request: `push!`

### ISSUE THREAD

**Issue by LilithHafner** [JuliaArrays/ElasticArrays.jl#45]
I'd like to be able to call `push!(::ElasticArray{N}, ::AbstractArray{N-1})`

**Comment by oschulz** [comment]
You can do that with `append!`, but there's no `push!` support on purpose: `push!` doesn't seem semantically suited as it's supposed to add an entry, but the entry type of an `ElasticArray{T,N}` is not `AbstractArray{T,N-1}`.

`push!` is available when combining ElasticArrays.jl with ArraysOfArrays.jl though. While ElasticArrays.jl and ArraysOfArrays.jl don't depend on each other, they were designed to be used together to implement resizable vectors-of-arrays that are backed by contiguous memory:

```
using ElasticArrays, ArraysOfArrays

flat_A = ElasticArray{Float64}(undef, 5, 4, 0)
A = VectorOfSimilarArrays(flat_A)
push!(A, rand(5, 4))
push!(A, rand(5, 4))
push!(A, rand(5, 4))

@assert flatview(A) === flat_A
@assert size(flat_A) == (5, 4, 3)
```

Will this suit your use case, @LilithHafner ?

**Comment by LilithHafner** [comment]
Yes, thank you! I see why `push!` is not supported.
