### ISSUE TITLE
Unused type variable in ctor

### ISSUE THREAD

**Issue by nhz2** [JuliaArrays/ElasticArrays.jl#49]
I get the following warning when I use ElasticArrays in Julia 1.8.3
```
WARNING: method definition for ElasticArray at /home/nathan/.julia/packages/ElasticArrays/uqU8T/src/elasticarray.jl:40 declares type variable M but does not use it.
```
https://github.com/JuliaArrays/ElasticArrays.jl/blob/964fbe2ccc33c9a4ee707ae1fcf10f845c2a1726/src/elasticarray.jl#L40-L42

**Comment by oschulz** [comment]
Oh, yes, we need to fix that, that stuff can cause type inference failures.
