### ISSUE TITLE
Register package

### ISSUE THREAD

**Issue by oschulz** [JuliaArrays/ElasticArrays.jl#7]
I guess things are in decent shape now and it's time to register the package (v0.1?). @garrison, @timholy anything you'd like to see changed/added before the first release?

**Comment by oschulz** [comment]
@garrison, I made a few small changes - could you give the package a quick test in your application, before I tag it?

**Comment by garrison** [comment]
Sounds good to me!  (All tests pass in my application, as well.)

**Comment by oschulz** [comment]
Registration PR submitted via attobot
